# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-07 02:50
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConservationCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folio', models.CharField(blank=True, help_text='External Identifier', max_length=255, verbose_name='Certificate Folio')),
                ('raw_document', models.TextField(blank=True, help_text='Base64 document', verbose_name='Raw Certificate')),
                ('reference', models.CharField(help_text='This ir our reference', max_length=255, verbose_name='Merkle Root used as reference')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={})),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
