# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-09 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0004_auto_20181027_1056'),
        ('nom151', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conservationcertificate',
            name='block',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blockchain.Block'),
        ),
        migrations.AlterField(
            model_name='conservationcertificate',
            name='reference',
            field=models.CharField(help_text='This ir our reference', max_length=255, unique=True, verbose_name='Merkle Root used as reference'),
        ),
    ]
