language: python
python:
  - "3.6"
install: "pip install -r requirements.txt"
before_script:
  - pip install flake8
  - pip install bandit
  - pip install coverage
script:
  - flake8
  - bandit -r ./
  - coverage run prescript/manage.py test
  - coverage report -m
