language: python
dist: xenial
python:
  - "3.6"
addons:
  postgresql: "9.6"
install: "pip install -r requirements.txt"
services:
  - postgresql
  - redis-server
before_script:
  - pip install flake8
  - pip install bandit
  - pip install coverage
script:
  - flake8
  - bandit -r ./
  - coverage run rexchain/manage.py test
  - coverage report -m
