version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: vagrant
      POSTGRES_PASSWORD: vagrant
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Django Web Application
  web:
    build: .
    command: >
      sh -c "echo 'Starting database setup...' &&
             python rexchain/manage.py migrate --verbosity=2 &&
             echo 'Loading fixtures...' &&
             python rexchain/manage.py loaddata ./rexchain/fixtures/initial_data.json --verbosity=2 &&
             echo 'Starting server...' &&
             python rexchain/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - config/docker.env
    depends_on:
      - db
      - redis

  # RQ Worker for background tasks
  worker:
    build: .
    command: python rexchain/manage.py rqworker high default low
    volumes:
      - .:/app
    env_file:
      - config/docker.env
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  redis_data: