# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-03 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='prescription',
        ),
        migrations.AddField(
            model_name='prescription',
            name='signature',
            field=models.TextField(blank=True, default=b'', verbose_name=b'Signature with PK and data transaction '),
        ),
        migrations.DeleteModel(
            name='Medication',
        ),
    ]
