# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-25 20:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_auto_20181003_0147'),
    ]

    operations = [
        migrations.RenameModel('Prescription', 'Payload')
    ]
