# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-24 19:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_auto_20181003_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name=b'Datetime object')),
                ('readable', models.BooleanField(default=False, verbose_name=b'Check if data is readable(synonym spent)')),
                ('is_valid', models.BooleanField(default=True, verbose_name=b'Check if signature validation was valid')),
                ('signature', models.TextField(blank=True, default=b'', verbose_name=b'Signature with PK and data transaction ')),
                ('hash_id', models.TextField(blank=True, default=b'', verbose_name=b'Hash for Blockchainize Object')),
                ('previous_hash', models.TextField(blank=True, default=b'0', verbose_name=b'Previous Hash for Blockchainize Object')),
                ('raw_msg', models.TextField(blank=True, default=b'', verbose_name=b'Chaining raw data of Blockchainize object for hashing purpose')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, verbose_name=b'Raw Data from Payload')),
                ('public_key', models.TextField(blank=True, default=True, verbose_name=b'An Hex representation of Public Key Object')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payloads', to='blockchain.Transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='transaction',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
