# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-27 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_auto_20181025_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(db_index=True, default=b'', help_text=b'Format: Base 58 and valid bitcoin address', max_length=255, verbose_name=b'Address to get transactions'),
        ),
        migrations.AlterField(
            model_name='payload',
            name='public_key',
            field=models.TextField(blank=True, db_index=True, default=True, verbose_name=b'An Hex representation of Public Key Object'),
        )
    ]
