# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0004_auto_20170709_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='public_key',
            field=models.CharField(blank=True, default=b'', max_length=2000),
        ),
    ]
