# Generated by Django 3.2.25 on 2024-09-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0005_auto_20220818_2307'),
    ]

    operations = [

        migrations.AlterField(
            model_name='payload',
            name='hash_id',
            field=models.TextField(blank=True, db_index=True, default='', verbose_name='Hash for Blockchainize Object'),
        ),
    ]
