# Generated by Django 4.2.18 on 2025-04-21 20:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("blockchain", "0006_auto_20240911_0002"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="txid",
            field=models.TextField(blank=True, db_index=True, default=""),
        ),
    ]
