# Generated by Django 4.2.18 on 2025-10-09 00:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0007_alter_address_address_alter_address_is_valid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(db_index=True, default='', help_text='Format: Base 58 and valid bitcoin address', max_length=255, verbose_name='Address to get transactions'),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_valid',
            field=models.BooleanField(blank=True, default=True, verbose_name='Check if address is valid'),
        ),
        migrations.AlterField(
            model_name='address',
            name='public_key_b64',
            field=models.TextField(default='', help_text='Format: Base 64', unique=True, verbose_name='Public Key'),
        ),
        migrations.AlterField(
            model_name='block',
            name='hash_block',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='block',
            name='hashcash',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='block',
            name='merkleroot',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='block',
            name='nonce',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='block',
            name='poetxid',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='block',
            name='previous_hash',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='payload',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='payload',
            name='is_valid',
            field=models.BooleanField(blank=True, default=True, verbose_name='Check if signature validation was valid'),
        ),
        migrations.AlterField(
            model_name='payload',
            name='previous_hash',
            field=models.TextField(blank=True, default='0', verbose_name='Previous Hash for Blockchainize Object'),
        ),
        migrations.AlterField(
            model_name='payload',
            name='public_key',
            field=models.TextField(blank=True, default=True, verbose_name='An Hex representation of Public Key Object'),
        ),
        migrations.AlterField(
            model_name='payload',
            name='raw_msg',
            field=models.TextField(blank=True, default='', verbose_name='Chaining raw data of Blockchainize object for hashing purpose'),
        ),
        migrations.AlterField(
            model_name='payload',
            name='readable',
            field=models.BooleanField(blank=True, default=False, verbose_name='Check if data is readable(synonym spent)'),
        ),
        migrations.AlterField(
            model_name='payload',
            name='signature',
            field=models.TextField(blank=True, default='', verbose_name='Signature with PK and data transaction'),
        ),
        migrations.AlterField(
            model_name='payload',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Datetime object'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_valid',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='previous_hash',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='raw_msg',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='signature',
            field=models.TextField(blank=True, default=''),
        ),
    ]
