# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0007_block_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='merkleroot',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
