# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 22:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0011_auto_20170724_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='public_key',
        ),
    ]
