# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 17:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0012_remove_medication_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=datetime.date(2017, 7, 26)),
        ),
    ]
