# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-30 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0016_auto_20180827_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='active',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='medication',
            name='dose',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='medication',
            name='drug_upc',
            field=models.TextField(blank=True, db_index=True, default=b''),
        ),
        migrations.AlterField(
            model_name='medication',
            name='frequency',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='medication',
            name='presentation',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='details',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='extras',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='location',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medic_cedula',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medic_hospital',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medic_name',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient_age',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient_name',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='previous_hash',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='rxid',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='signature',
            field=models.TextField(blank=True, default=b'', null=True),
        ),
    ]
