# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-14 17:21
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0018_auto_20180830_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('raw_msg', models.TextField(blank=True, default=b'')),
                ('signature', models.TextField(blank=True, default=b'')),
                ('is_valid', models.BooleanField(default=False)),
                ('txid', models.TextField(blank=True, default=b'')),
                ('previous_hash', models.TextField(blank=True, default=b'')),
                ('details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={})),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='blockchain.Block')),
            ],
        ),
    ]
