# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-19 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0020_auto_20180914_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_key_b64', models.TextField(default=b'', help_text=b'Format: Base 64', unique=True, verbose_name=b'Public Key')),
                ('address', models.CharField(default=b'', help_text=b'Format: Base 58 and valid bitcoin address', max_length=255, verbose_name=b'Address to get transactions')),
                ('is_valid', models.BooleanField(default=True, verbose_name=b'Check if address is valid')),
            ],
            options={
                'ordering': ['created_at'],
                'verbose_name_plural': 'Valid Bitcoin Addresses',
            },
        ),
    ]
