# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='raw_msg',
            field=models.TextField(blank=True, default=b'', max_length=10000),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='signature',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
    ]
