# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_remove_prescription_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='location_lat',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='location_lon',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='private_key',
            field=models.CharField(blank=True, default=b'', max_length=2000),
        ),
    ]
