# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0005_auto_20170709_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='hash_anterior',
        ),
        migrations.AlterField(
            model_name='block',
            name='hash_block',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
    ]
