# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 04:50
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0006_auto_20170712_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
