# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0010_block_previous_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='instructions',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='diagnosis',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='raw_msg',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
