# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-05 04:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0014_auto_20180204_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='poetxid',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='private_key',
            field=models.CharField(blank=True, default=b'', max_length=3000),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='public_key',
            field=models.CharField(blank=True, default=b'', max_length=3000),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 2, 5, 4, 17, 48, 920753, tzinfo=utc)),
        ),
    ]
