# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-06 03:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0013_auto_20170726_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='poetxid',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
        migrations.AddField(
            model_name='prescription',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block', to='blockchain.Block'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='rxid',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='private_key',
            field=models.CharField(blank=True, default=b'', max_length=3000),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='public_key',
            field=models.CharField(blank=True, default=b'', max_length=3000),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='signature',
            field=models.CharField(blank=True, default=b'', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 2, 6, 3, 10, 17, 388360, tzinfo=utc)),
        ),
    ]
