# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-28 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0014_auto_20180205_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='hashcash',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
        migrations.AddField(
            model_name='block',
            name='nonce',
            field=models.CharField(blank=True, default=b'', max_length=50),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
