# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-04 07:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0014_auto_20180204_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='signature',
            field=models.CharField(blank=True, default=b'', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 2, 4, 7, 26, 25, 963304, tzinfo=utc)),
        ),
    ]
