# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-05 20:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0015_auto_20180204_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block', to='blockchain.Block'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 2, 5, 20, 11, 13, 293798, tzinfo=utc)),
        ),
    ]
