# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-12 06:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0016_auto_20180508_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
