# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-30 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0017_auto_20180830_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='presentation',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
